# Generated by Django 4.2.4 on 2023-08-19 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('contact', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('contact', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40)),
                ('quantite', models.IntegerField(default=0)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinwcs.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('u', 'utilisation'), ('e', 'emprunt')], default='e', max_length=1)),
                ('statut', models.CharField(choices=[('r', 'remis'), ('n', 'non-remis')], default='n', max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magasinwcs.client')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinwcs.employe')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinwcs.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magasinwcs.fournisseur')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinwcs.materiel')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='fonction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinwcs.fonction'),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magasinwcs.fournisseur')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinwcs.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('s', 'super-admin'), ('n', 'normal')], default='n', max_length=1)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinwcs.employe')),
            ],
        ),
    ]
