# Generated by Django 4.2.4 on 2023-09-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinwcs', '0004_alter_client_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
