# Generated by Django 4.2.4 on 2023-09-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinwcs', '0005_utilisation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisation',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
    ]
