# Generated by Django 4.2.4 on 2023-09-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinwcs', '0007_alter_commande_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='traitement',
            field=models.CharField(choices=[('t', 'traitré'), ('n', 'non-traité')], default='n', max_length=1),
        ),
    ]
