# Generated by Django 4.2.4 on 2023-09-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinwcs', '0008_commande_traitement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
