# Generated by Django 4.2.4 on 2023-09-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinwcs', '0009_commande_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
    ]
