# Generated by Django 4.2.4 on 2023-09-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinwcs', '0011_reception_delete_livraison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrateur',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='administrateur',
            name='password',
        ),
        migrations.AddField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='password',
            field=models.CharField(default='AZERTY', max_length=20),
        ),
    ]
