# Generated by Django 4.2.4 on 2023-09-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinwcs', '0012_remove_administrateur_employe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
