# Generated by Django 4.2.4 on 2023-09-05 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasinwcs', '0013_alter_employe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='magasinwcs.employe'),
        ),
    ]
