# Generated by Django 4.2.4 on 2023-09-29 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasinwcs', '0016_delete_panier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('prix_unitaire', models.IntegerField(default=0)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinwcs.employe')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinwcs.fournisseur')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinwcs.materiel')),
            ],
        ),
    ]
