# Generated by Django 4.2.4 on 2023-09-29 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasinwcs', '0017_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='panier',
            name='fournisseur',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='magasinwcs.fournisseur'),
        ),
    ]
