# Generated by Django 4.2.4 on 2023-09-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinwcs', '0019_alter_panier_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
