# Generated by Django 4.2.4 on 2023-09-30 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasinwcs', '0020_panier_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magasinwcs.client'),
        ),
        migrations.AddField(
            model_name='panier',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to='magasinwcs.employe'),
        ),
        migrations.AddField(
            model_name='panier',
            name='utilisation',
            field=models.CharField(blank=True, choices=[('u', 'utilisation'), ('e', 'emprunt')], default='e', max_length=1),
        ),
        migrations.AlterField(
            model_name='panier',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe', to='magasinwcs.employe'),
        ),
    ]
