# Generated by Django 4.2.4 on 2023-10-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinwcs', '0021_panier_client_panier_utilisateur_panier_utilisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
