# Generated by Django 4.2.4 on 2023-10-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinwcs', '0022_client_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
