# Generated by Django 4.2.4 on 2023-10-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinwcs', '0023_fournisseur_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='prix_unitaire',
        ),
        migrations.AddField(
            model_name='materiel',
            name='prix_unitaire',
            field=models.IntegerField(default=0),
        ),
    ]
